<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

/**
 * @var Magento\Checkout\Block\Onepage\Success $block
 */

?>

<div class="checkout-success">
    <?php if ($block->getOrderId()):?>
        <?php if ($block->getCanViewOrder()) :?>
            <div class="circle">
                <div class="circle__check1"></div>
                <div class="circle__check2"></div>
            </div>
            <h2 class="checkout__title"><b><?= $block->escapeHtml(__('order confirmation')) ?></b></h2>
            <p class="checkout__ty"><?= $block->escapeHtml(__('Thank you for shopping')) ?></p>
            <p class="checkout__order"><?= __('Order number: %1.', sprintf('<a href="%s" class="order-number"><strong>%s</strong></a>', $block->escapeHtml($block->getViewOrderUrl()), $block->escapeHtml($block->getOrderId()))) ?></p>
        <?php  else :?>
            <div class="circle">
                <div class="circle__check1"></div>
                <div class="circle__check2"></div>
            </div>
            <h2 class="checkout__title"><?= $block->escapeHtml(__('order confirmation')) ?></h2>
            <p class="checkout__ty"><?= $block->escapeHtml(__('Thank you for shopping')) ?></p>
            <p class="checkout__order"><?= __('Your order # is: <span>%1</span>.', $block->escapeHtml($block->getOrderId())) ?></p>
        <?php endif;?>
    <?php endif;?>

    <?= $block->getAdditionalInfoHtml() ?>
</div>

<div class="checkout__border"></div>
