<?php
/**
 * @var \Magento\Checkout\Block\Onepage\Success $block
 */
?>

<div class="checkout__promotion">
    <div class="checkout__info">
        <div class="checkout__header">
            <h4 class="checkout__actualheader"><?= $block->escapeHtml(__('order details'))?></h4>
        </div>
        <div class="checkout__descr">
            <p><?= $block->escapeHtml(__('Your order will be delivered within 1-2 days. Please make sure that you have entered your complete address and correct contact details, as this will reduce any potential delays in your shipment.')) ?></p>
        </div>
    </div>
    <a class="checkout__info" href="http://neekeetah.test/promotion/promo/view/">
        <div class="checkout__header">
            <h4 class="checkout__actualheader"><?= $block->escapeHtml(__('Invite friends, get rewards!')) ?></h4>
            <img class="chevronright" src="https://upload.wikimedia.org/wikipedia/commons/thumb/6/6f/Ic_chevron_right_48px.svg/768px-Ic_chevron_right_48px.svg.png" alt="goRight"/>
        </div>
        <div class="checkout__descr">
            <p><?= $block->escapeHtml(__('100$ Store Credit for you, 100$ Store Credit for your friend. Tell your friends to enter your coupon checkout and they will receive 30% off their first purchase.')) ?></p>
        </div>
    </a>

    <a class="checkout__info mobile" href="http://neekeetah.test/promotion/promo/view/">
        <div class="checkout__header">
            <h4 class="checkout__actualheader"><?= $block->escapeHtml(__('Invite friends, get rewards!')) ?></h4>
            <img class="chevronright" src="https://upload.wikimedia.org/wikipedia/commons/thumb/6/6f/Ic_chevron_right_48px.svg/768px-Ic_chevron_right_48px.svg.png" alt="goRight"/>
        </div>
        <div class="checkout__descr">
            <p><?= $block->escapeHtml(__("Introduce a friend and You'll get 30 $ in Store Credit to spend and they get 100 $ off")) ?></p>
        </div>
    </a>

    <div class="actions-toolbar">
        <div class="primary">
            <a class="action primary continue" href="<?= /* @escapeNotVerified */ $block->getUrl() ?>"><span><?= /* @escapeNotVerified */ __('Continue Shopping') ?></span></a>
        </div>
    </div>
</div>
